name: test

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.dart"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/dart_test.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.dart"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/dart_test.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Output Commit Information
        run: |
          echo "触发此次action的提交ID: ${{ github.sha }}"
          GITHASH=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "GITHASH=$GITHASH" >> $GITHUB_ENV
          echo "GITHASH (前7位): $GITHASH"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.38.10"

      - run: flutter pub get
      - run: flutter test
